import { Meeting, Folder, Speaker } from "./types";

export const SPEAKER_COLORS = [
  "#6366f1", "#f59e0b", "#10b981", "#ef4444", "#8b5cf6", "#06b6d4", "#f97316", "#84cc16"
];

export const mockFolders: Folder[] = [
  { id: "f1", name: "Client Meetings", color: "#6366f1", meetingCount: 8 },
  { id: "f2", name: "Internal", color: "#10b981", meetingCount: 12 },
  { id: "f3", name: "Q3 Planning", color: "#f59e0b", meetingCount: 5 },
  { id: "f4", name: "Board", color: "#ef4444", meetingCount: 3 },
];

const speakers1: Speaker[] = [
  { id: "s1", name: "Mike Johnson", color: "#6366f1" },
  { id: "s2", name: "Jovit Aleria", color: "#f59e0b" },
  { id: "s3", name: "Sarah Chen", color: "#10b981" },
];

const speakers2: Speaker[] = [
  { id: "s4", name: "David Park", color: "#6366f1" },
  { id: "s5", name: "Emily Torres", color: "#ef4444" },
];

export const mockMeetings: Meeting[] = [
  {
    id: "m1",
    title: "Q3 Revenue Review & Client Strategy",
    date: "2026-06-25T14:00:00",
    duration: 3720,
    participants: ["Mike Johnson", "Jovit Aleria", "Sarah Chen"],
    status: "completed",
    tags: ["Q3", "revenue", "strategy"],
    team: "Executive",
    folderId: "f1",
    recordingUrl: "/demo/recording.mp3",
    isFavorite: true,
    createdBy: "Jovit Aleria",
    speakers: speakers1,
    transcript: [
      { id: "t1", speakerId: "s1", startTime: 0, endTime: 12, text: "Good morning everyone. Thanks for joining today's Q3 revenue review. I'll start with the high-level numbers." },
      { id: "t2", speakerId: "s2", startTime: 14, endTime: 28, text: "Thanks Mike. Before you begin, I just want to confirm—are we covering the Hartmann account in this session?" },
      { id: "t3", speakerId: "s1", startTime: 30, endTime: 52, text: "Yes, Hartmann is on the agenda for the second half. We'll go through overall revenue first, then break down by client. The Hartmann account has some nuances we need to address." },
      { id: "t4", speakerId: "s3", startTime: 55, endTime: 78, text: "I've pulled together the updated projections. We're currently sitting at 94% of Q3 target with two weeks to close. The Hartmann renewal is the biggest variable." },
      { id: "t5", speakerId: "s2", startTime: 80, endTime: 105, text: "Right. I had a call with their CFO on Monday. They're leaning toward a multi-year deal, which would be great, but they want a 12% discount on years two and three. We need to decide if that's acceptable." },
      { id: "t6", speakerId: "s1", startTime: 108, endTime: 135, text: "Given our margin targets, we could go to 10% max. I'd want finance to run the numbers before we commit. Sarah, can you get that analysis to us by Friday?" },
      { id: "t7", speakerId: "s3", startTime: 137, endTime: 158, text: "Absolutely. I'll have a full scenario analysis by Thursday EOD. I'll look at 8%, 10%, and 12% discount scenarios with 3-year and 5-year projections." },
      { id: "t8", speakerId: "s2", startTime: 160, endTime: 180, text: "Perfect. I'll use that to go back to Hartmann on Monday. Let's also discuss the new upsell opportunity with their Chicago office." },
    ],
    summaries: {
      executive: "The Q3 revenue review confirmed the team is at 94% of target with two weeks remaining. The critical variable is the Hartmann account renewal, where the client is requesting a 12% multi-year discount. Leadership agreed to evaluate a maximum 10% discount pending a finance scenario analysis due Thursday.",
      bullet: "• At 94% of Q3 revenue target with two weeks to close\n• Hartmann account renewal is the primary risk/opportunity\n• Client requesting 12% discount on multi-year deal (years 2-3)\n• Internal ceiling set at 10% pending finance analysis\n• Sarah Chen to deliver 3-scenario analysis by Thursday EOD\n• Follow-up with Hartmann CFO scheduled for Monday\n• Chicago office upsell opportunity to be explored",
      detailed: "The meeting opened with a review of Q3 performance metrics. The team is performing at 94% of the quarterly revenue target with approximately two weeks remaining in the period. Mike Johnson presented the top-level numbers before handing off to Sarah Chen for detailed projections.\n\nThe primary discussion centered on the Hartmann account renewal. Jovit Aleria reported that the Hartmann CFO is interested in a multi-year arrangement but has requested a 12% discount on years two and three. The team debated the acceptability of this discount in the context of current margin targets.\n\nMike Johnson indicated the company could authorize a maximum 10% discount, subject to a financial analysis. Sarah Chen agreed to prepare a comprehensive scenario analysis covering 8%, 10%, and 12% discount options across both 3-year and 5-year contract terms. This analysis is due Thursday EOD.\n\nJovit Aleria will use the analysis to prepare for a follow-up conversation with the Hartmann CFO on Monday. The team also agreed to explore an upsell opportunity with Hartmann's Chicago office, which was deferred to the next meeting.",
      oneSentence: "The team is at 94% of Q3 revenue target, with the Hartmann account renewal—potentially with a 10% multi-year discount—as the key remaining opportunity to close the quarter.",
      clientFriendly: "We had a productive strategy session reviewing Q3 progress and discussing the path to a strong quarter close. Key highlights include being near target with two weeks remaining and advancing discussions on a long-term partnership opportunity that could deliver significant value for both organizations.",
      management: "Q3 revenue execution is on track at 94% of plan. The Hartmann account renewal, representing a significant multi-year contract, is in final negotiation. Finance has been tasked with scenario modeling to inform the final discount position. A decision is expected by end of next week.",
    },
    actionItems: [
      { id: "a1", task: "Prepare 3-scenario discount analysis (8%, 10%, 12%) for Hartmann deal", assignee: "Sarah Chen", dueDate: "2026-06-27", priority: "high", status: "in_progress", notes: "Include 3-year and 5-year projections" },
      { id: "a2", task: "Follow-up call with Hartmann CFO to present multi-year proposal", assignee: "Jovit Aleria", dueDate: "2026-06-30", priority: "high", status: "open" },
      { id: "a3", task: "Research Chicago office upsell opportunity and prepare brief", assignee: "Mike Johnson", dueDate: "2026-07-03", priority: "medium", status: "open" },
    ],
    minutes: {
      title: "Q3 Revenue Review & Client Strategy",
      date: "June 25, 2026",
      time: "2:00 PM",
      duration: "1 hour 2 minutes",
      participants: ["Mike Johnson", "Jovit Aleria", "Sarah Chen"],
      objectives: ["Review Q3 revenue performance against target", "Discuss Hartmann account renewal strategy", "Assign follow-up responsibilities"],
      agenda: ["Q3 revenue overview", "Hartmann account update", "Discount scenario planning", "Next steps and assignments"],
      discussionSummary: "The meeting opened with a high-level review of Q3 performance. The team confirmed the organization is tracking at 94% of its quarterly revenue target with approximately two weeks remaining. Sarah Chen presented updated projections, identifying the Hartmann account renewal as the primary variable that could determine whether the team closes the quarter at or above plan.\n\nJovit Aleria updated the group on a conversation held Monday with the Hartmann CFO. The client has expressed strong interest in a multi-year arrangement (3 to 5 years) but is seeking a 12% discount on contract years two and three. After discussion, the group agreed that a maximum internal authorization of 10% was reasonable, contingent on finance approval.\n\nSarah Chen committed to delivering a three-scenario financial model (8%, 10%, 12% discount) with both 3-year and 5-year contract projections by Thursday EOD. This analysis will serve as the basis for the Monday negotiation with Hartmann.\n\nThe team briefly discussed a new upsell opportunity with Hartmann's Chicago office and agreed to schedule a dedicated discussion once the renewal is concluded.",
      decisions: [
        "Maximum authorized discount for Hartmann multi-year deal is 10%, pending finance analysis",
        "Finance scenario analysis will be completed before any commitment is made to Hartmann",
        "Chicago office upsell discussion deferred to a subsequent meeting",
      ],
      actionItems: [
        { id: "a1", task: "Prepare discount scenario analysis", assignee: "Sarah Chen", dueDate: "2026-06-27", priority: "high", status: "in_progress" },
        { id: "a2", task: "Follow-up with Hartmann CFO", assignee: "Jovit Aleria", dueDate: "2026-06-30", priority: "high", status: "open" },
        { id: "a3", task: "Chicago upsell brief", assignee: "Mike Johnson", dueDate: "2026-07-03", priority: "medium", status: "open" },
      ],
      risks: [
        "Hartmann may not accept a 10% cap, risking deal delay or loss",
        "Q3 target miss if Hartmann renewal does not close before quarter end",
      ],
      followUpItems: [
        "Hartmann Chicago office upsell assessment",
        "Review remaining pipeline to identify additional Q3 close opportunities",
      ],
      nextMeeting: "July 2, 2026 — Full Q3 close review",
      preparedBy: "MinuteFlow AI Assistant",
    },
  },
  {
    id: "m2",
    title: "Product Roadmap Planning — H2 2026",
    date: "2026-06-24T10:00:00",
    duration: 5400,
    participants: ["David Park", "Emily Torres"],
    status: "completed",
    tags: ["product", "roadmap", "H2"],
    team: "Product",
    folderId: "f2",
    isFavorite: false,
    createdBy: "David Park",
    speakers: speakers2,
    transcript: [
      { id: "t1", speakerId: "s4", startTime: 0, endTime: 18, text: "Alright, let's lock in the H2 roadmap. We've got the engineering capacity numbers from last week. I want to prioritize the three initiatives that will have the most customer impact." },
      { id: "t2", speakerId: "s5", startTime: 20, endTime: 42, text: "Based on the customer interviews, the top requests are real-time collaboration, an improved mobile experience, and better API documentation. The collaboration feature alone has 47 open feature requests." },
      { id: "t3", speakerId: "s4", startTime: 44, endTime: 68, text: "Real-time collaboration is also strategically important. It's the main reason we're losing deals to Notion and Confluence. If we can ship a solid MVP in Q3, I think we can start converting some of those losses." },
    ],
    summaries: {
      executive: "The H2 2026 product roadmap session identified three priority initiatives: real-time collaboration, mobile experience improvements, and enhanced API documentation. Real-time collaboration was flagged as the highest strategic priority based on competitive analysis.",
      bullet: "• Three H2 priorities identified: real-time collaboration, mobile UX, API docs\n• 47 open feature requests for real-time collaboration\n• Real-time collab MVP targeted for Q3\n• Key competitive differentiator vs. Notion and Confluence",
      detailed: "David Park and Emily Torres met to finalize the H2 product roadmap based on available engineering capacity and customer research. Emily Torres presented insights from recent customer interviews, identifying the three most requested features. David Park emphasized the competitive angle, noting that real-time collaboration is a primary factor in competitive losses.",
      oneSentence: "The team aligned on three H2 priorities—real-time collaboration, mobile UX, and API docs—with collaboration as the strategic flagship for Q3.",
      clientFriendly: "Our product team has completed planning for the second half of 2026, with a focus on features most requested by customers including real-time collaboration and an improved mobile experience.",
      management: "H2 roadmap prioritization is complete. Top three initiatives aligned to customer demand and competitive positioning. Real-time collaboration MVP is the Q3 flagship deliverable.",
    },
    actionItems: [
      { id: "a4", task: "Finalize engineering estimates for real-time collaboration MVP", assignee: "David Park", dueDate: "2026-06-28", priority: "high", status: "open" },
      { id: "a5", task: "Create mobile UX improvement spec", assignee: "Emily Torres", dueDate: "2026-07-05", priority: "medium", status: "open" },
    ],
    minutes: {
      title: "Product Roadmap Planning — H2 2026",
      date: "June 24, 2026",
      time: "10:00 AM",
      duration: "1 hour 30 minutes",
      participants: ["David Park", "Emily Torres"],
      objectives: ["Finalize H2 2026 product roadmap", "Prioritize initiatives based on customer impact and capacity"],
      agenda: ["Engineering capacity review", "Customer research summary", "Initiative prioritization", "Q3 targets"],
      discussionSummary: "The session focused on translating customer research and engineering capacity into a prioritized H2 roadmap. Emily Torres presented findings from customer interviews, with real-time collaboration, mobile UX, and API documentation emerging as the top three requests. David Park framed the strategic importance of real-time collaboration in the context of competitive deals lost to Notion and Confluence.",
      decisions: ["Real-time collaboration is the Q3 flagship initiative", "Mobile UX and API docs are H2 priorities following collaboration"],
      actionItems: [
        { id: "a4", task: "Finalize engineering estimates for real-time collaboration MVP", assignee: "David Park", dueDate: "2026-06-28", priority: "high", status: "open" },
        { id: "a5", task: "Create mobile UX improvement spec", assignee: "Emily Torres", dueDate: "2026-07-05", priority: "medium", status: "open" },
      ],
      risks: ["Engineering capacity constraints may affect Q3 timeline"],
      followUpItems: ["Detailed sprint planning for real-time collaboration", "Customer communication on roadmap timeline"],
      nextMeeting: "July 7, 2026 — Sprint planning kickoff",
      preparedBy: "MinuteFlow AI Assistant",
    },
  },
  {
    id: "m3",
    title: "Weekly Team Standup",
    date: "2026-06-23T09:00:00",
    duration: 1800,
    participants: ["Mike Johnson", "Jovit Aleria", "Sarah Chen", "David Park"],
    status: "completed",
    tags: ["standup", "weekly"],
    team: "All Hands",
    folderId: "f2",
    isFavorite: false,
    createdBy: "Mike Johnson",
    speakers: speakers1,
    summaries: {
      executive: "Weekly standup covered project status updates across teams. No blockers identified. All initiatives on track.",
      bullet: "• All teams on track\n• No blockers reported\n• Q3 targets confirmed achievable",
      detailed: "Standard weekly standup. Each team reported on progress. No escalations needed.",
      oneSentence: "All teams confirmed progress on track with no blockers during the weekly standup.",
      clientFriendly: "Our weekly team sync confirmed all active projects are progressing as planned.",
      management: "Weekly standup completed. No issues escalated. Teams aligned on priorities.",
    },
    actionItems: [],
  },
  {
    id: "m4",
    title: "Annual Budget Review 2027",
    date: "2026-06-20T13:00:00",
    duration: 7200,
    participants: ["Mike Johnson", "Jovit Aleria"],
    status: "completed",
    tags: ["budget", "annual", "finance"],
    team: "Executive",
    folderId: "f4",
    isFavorite: true,
    createdBy: "Jovit Aleria",
    speakers: [speakers1[0], speakers1[1]],
    summaries: {
      executive: "Annual budget review for 2027 completed. Total budget set at $4.2M, a 15% increase over 2026. Key investments in engineering headcount and sales expansion.",
      bullet: "• 2027 budget: $4.2M (15% YoY increase)\n• Headcount: +8 engineering, +3 sales\n• New office in Austin planned for Q2 2027\n• Marketing budget increased 22%",
      detailed: "Comprehensive budget review covering all departments for fiscal year 2027. Engineering receives the largest allocation increase to support product roadmap ambitions. Sales expansion budget approved for East Coast market.",
      oneSentence: "The 2027 budget of $4.2M was approved with significant increases in engineering and sales headcount.",
      clientFriendly: "We completed our annual planning process and are positioned for strong growth in 2027.",
      management: "FY2027 budget approved at $4.2M. Major investments in talent and market expansion approved.",
    },
    actionItems: [
      { id: "a6", task: "Prepare hiring plans for 8 engineering roles", assignee: "Mike Johnson", dueDate: "2026-07-15", priority: "high", status: "open" },
    ],
  },
  {
    id: "m5",
    title: "New Client Onboarding — Meridian Group",
    date: "2026-06-18T15:00:00",
    duration: 2700,
    participants: ["Jovit Aleria", "Sarah Chen"],
    status: "transcribing",
    tags: ["onboarding", "client"],
    team: "Client Success",
    folderId: "f1",
    isFavorite: false,
    createdBy: "Jovit Aleria",
    processingProgress: 65,
  },
  {
    id: "m6",
    title: "Engineering Architecture Review",
    date: "2026-06-17T11:00:00",
    duration: 4500,
    participants: ["David Park", "Emily Torres", "Mike Johnson"],
    status: "uploading",
    tags: ["engineering", "architecture"],
    team: "Engineering",
    folderId: "f2",
    isFavorite: false,
    createdBy: "David Park",
    processingProgress: 30,
  },
];
